### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by amarabha** [karan1095/Nagpur-Metro-Facilitator#1]
when I run the application I face issue with this URL (http://cgossip.in/karanread.php) can you help me in this issue please. my email is (anas_42003@hotmail.com)

**Comment by karan1095** [comment]
Hi,
   The site http://cgossip.in/karanread.php is down. So, what you can do is
comment out that components i.e the screen which shows location tracking of
metro.

**Comment by amarabha** [comment]
thanks for your quick reply, but how I can track the location of metro if it down?. is it possible to share it with me?

**Comment by amarabha** [comment]
Dear Karan,
I need your help in that issue please.

**Comment by karan1095** [comment]
Hi,
      but how I can track the location of metro if it down?. for that what you need to do is instead of using http://cgossip.in/karanread.php you can use another site of yours write a small server-side php script over there. the script will take (latitude, longitude) co-ordinate from a GPS device and send those co-ordinate to your app. As a GPS device, you can use another mobile app. for that you need to create another small app that will send its location in form ((latitude, longitude)to the server.

**Comment by karan1095** [comment]
you can use this as location sending app https://github.com/karan1095/LocationSenderApp.git

**Comment by amarabha** [comment]
thank you. and I appreciate your support
